# Generated by Django 3.2.5 on 2021-08-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210802_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubRubricManager',
        ),
    ]
